**Bag of Words**

In [48]:
# import required libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import nltk
from nltk.corpus import stopwords

In [6]:
data = {
    "review": [
        "I absolutely love this phone! The camera quality is fantastic and battery lasts all day.",
        "Terrible experience. The screen broke within a week, and customer service was useless.",
        "Great value for money. Performance is smooth and build quality feels premium.",
        "The laptop overheats and the battery drains too fast. Very disappointed.",
        "Excellent sound quality and very comfortable to wear. Highly recommend these headphones!",
        "Worst product I’ve ever bought. It stopped working after two days.",
        "Amazing performance and display. Totally worth the price.",
        "Poor design and fragile build. I regret buying this item.",
        "Fast delivery and great packaging. The product works as expected.",
        "Customer support was unhelpful. Will not buy from this brand again."
    ],
    "sentiment": [
        "positive", "negative", "positive", "negative", "positive",
        "negative", "positive", "negative", "positive", "negative"
    ]
}

In [11]:
df=pd.DataFrame(data)
df

                                              review sentiment
0  I absolutely love this phone! The camera quali...  positive
1  Terrible experience. The screen broke within a...  negative
2  Great value for money. Performance is smooth a...  positive
3  The laptop overheats and the battery drains to...  negative
4  Excellent sound quality and very comfortable t...  positive
5  Worst product I’ve ever bought. It stopped wor...  negative
6  Amazing performance and display. Totally worth...  positive
7  Poor design and fragile build. I regret buying...  negative
8  Fast delivery and great packaging. The product...  positive
9  Customer support was unhelpful. Will not buy f...  negative

In [12]:
#function to lower and clean data
def clean_text(text):
  text=text.lower()
  text=re.sub(r'[^a-zA-Z0-9\s]','',text)
  text=' '.join([word for word in text.split() if word not in stopwords.words('english')])
  return text

In [13]:
df['clean_review']=df['review']
df

                                              review  ...                                       clean_review
0  I absolutely love this phone! The camera quali...  ...  I absolutely love this phone! The camera quali...
1  Terrible experience. The screen broke within a...  ...  Terrible experience. The screen broke within a...
2  Great value for money. Performance is smooth a...  ...  Great value for money. Performance is smooth a...
3  The laptop overheats and the battery drains to...  ...  The laptop overheats and the battery drains to...
4  Excellent sound quality and very comfortable t...  ...  Excellent sound quality and very comfortable t...
5  Worst product I’ve ever bought. It stopped wor...  ...  Worst product I’ve ever bought. It stopped wor...
6  Amazing performance and display. Totally worth...  ...  Amazing performance and display. Totally worth...
7  Poor design and fragile build. I regret buying...  ...  Poor design and fragile build. I regret buying...
8  Fast delivery and great packaging. The product...  ...  Fast delivery and great packaging. The product...
9  Customer support was unhelpful. Will not buy f...  ...  Customer support was unhelpful. Will not buy f...

[10 rows x 3 columns]

In [15]:
cv=CountVectorizer(max_features=20)
X=cv.fit_transform(df['clean_review']).toarray()
y=df['sentiment']
print("Top 20 Word in Features X")
cv.get_feature_names_out()
bow_df=pd.DataFrame(X,columns=cv.get_feature_names_out())
bow_df

Top 20 Word in Features X

   and  as  battery  bought  build  ...  quality  the  this  very  was
0    1   0        1       0      0  ...        1    1     1     0    0
1    1   0        0       0      0  ...        0    1     0     0    1
2    1   0        0       0      1  ...        1    0     0     0    0
3    1   0        1       0      0  ...        0    2     0     1    0
4    1   0        0       0      0  ...        1    0     0     1    0
5    0   0        0       1      0  ...        0    0     0     0    0
6    1   0        0       0      0  ...        0    1     0     0    0
7    1   0        0       0      1  ...        0    0     1     0    0
8    1   1        0       0      0  ...        0    1     0     0    0
9    0   0        0       0      0  ...        0    0     1     0    1

[10 rows x 20 columns]

In [ ]:
X_train,y_train, X_test

In [ ]:
# user prediction
# taking review from user
print("Enter your review below : \n")
user_review=input("Enter your product review : ")

#clean the review
user_review=clean_text(user_review)
user_review_bow=cv.transform([user_review]).toarray()

#predict using model
user_review_bow=cv.transform(user_review_bow)

#output predicted sentiment
print("\n Cleaned Review",user_review)
print("\n Predicted Sentiment : ",user_sentiment[0])

**Practice Exercise - One**

input_text="Natural Language Processing is going to help you out in near future. You have to remember this for getting interview calls"

**Do the following Tasks**


1.   Splits text into words/token (show the individual word token)
2.   Clean Tokens (show clean token)
3. Remove Stop words (show token after removing stop words)
4. Stemming (Show the words in their root forms)
5. Lemmatization (show lemma words)

In [32]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer,WordNetLemmatizer

import re

In [34]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [35]:
input_text = "Natural Language Processing is going to help you out in near future. You have to remember this for getting interview calls"

In [36]:
# 1 Tokenization
tokens=word_tokenize(input_text)
print("Individual word token")
tokens

Individual word token

['Natural',
 'Language',
 'Processing',
 'is',
 'going',
 'to',
 'help',
 'you',
 'out',
 'in',
 'near',
 'future',
 '.',
 'You',
 'have',
 'to',
 'remember',
 'this',
 'for',
 'getting',
 'interview',
 'calls']

In [37]:
# 2 clean token
clean_tokens=[re.sub(r'[^a-zA-Z]','',token.lower()) for token in tokens if token.isalpha()]
clean_tokens

['natural',
 'language',
 'processing',
 'is',
 'going',
 'to',
 'help',
 'you',
 'out',
 'in',
 'near',
 'future',
 'you',
 'have',
 'to',
 'remember',
 'this',
 'for',
 'getting',
 'interview',
 'calls']

In [38]:
# 3 remove stop words
stop_words=set(stopwords.words('english'))

filtered_tokens=[token for token in clean_tokens if token not in stop_words]
print('token after removing stop words')
filtered_tokens

token after removing stop words

['natural',
 'language',
 'processing',
 'going',
 'help',
 'near',
 'future',
 'remember',
 'getting',
 'interview',
 'calls']

In [42]:
#4 stemming (show the words in their root forms)
stemmer=PorterStemmer()
stemmed_tokens=[stemmer.stem(token) for token in filtered_tokens]
print('words in their root forms')
stemmed_tokens

words in their root forms

['natur',
 'languag',
 'process',
 'go',
 'help',
 'near',
 'futur',
 'rememb',
 'get',
 'interview',
 'call']

In [43]:
# 5 lemmatization (show lemma words)
lemmatizer=WordNetLemmatizer()
lemmatized_tokens=[lemmatizer.lemmatize(token) for token in filtered_tokens]
print('lemma words')
lemmatized_tokens

lemma words

['natural',
 'language',
 'processing',
 'going',
 'help',
 'near',
 'future',
 'remember',
 'getting',
 'interview',
 'call']

In [49]:
tfidf=TfidfVectorizer()
matrix=tfidf.fit_transform(lemmatized_tokens)
matrix
df=pd.DataFrame(matrix.toarray(),columns=tfidf.get_feature_names_out())
df

    call  future  getting  going  ...  natural  near  processing  remember
0    0.0     0.0      0.0    0.0  ...      1.0   0.0         0.0       0.0
1    0.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       0.0
2    0.0     0.0      0.0    0.0  ...      0.0   0.0         1.0       0.0
3    0.0     0.0      0.0    1.0  ...      0.0   0.0         0.0       0.0
4    0.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       0.0
5    0.0     0.0      0.0    0.0  ...      0.0   1.0         0.0       0.0
6    0.0     1.0      0.0    0.0  ...      0.0   0.0         0.0       0.0
7    0.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       1.0
8    0.0     0.0      1.0    0.0  ...      0.0   0.0         0.0       0.0
9    0.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       0.0
10   1.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       0.0

[11 rows x 11 columns]

**TF-IDF Example 2**

In [50]:
corpus=["Python developer required with strong coding skills",
        "Experience in REST API, Automation,Jenkins, Flask and Python ",
        "Looking for machine learning engineer familiar with NLP, Supervised, Unsupervised and Deep Learning"]

In [56]:
tfidf = TfidfVectorizer()

# Fit and transform the corpus
matrix = tfidf.fit_transform(corpus)

# Convert to DataFrame for readability
df = pd.DataFrame(matrix.toarray(), columns=tfidf.get_feature_names_out())

# Display the TF-IDF matrix
print(df)

       and       api  automation  ...  supervised  unsupervised      with
0  0.00000  0.000000    0.000000  ...    0.000000      0.000000  0.306504
1  0.26629  0.350139    0.350139  ...    0.000000      0.000000  0.000000
2  0.20213  0.000000    0.000000  ...    0.265777      0.265777  0.202130

[3 rows x 25 columns]

In [57]:
print('\n Top weighted terms')
print(df.mean().sort_values(ascending=False).head(10))

 Top weighted terms
python       0.190931
learning     0.177185
with         0.169545
and          0.156140
coding       0.134339
skills       0.134339
developer    0.134339
strong       0.134339
required     0.134339
in           0.116713
dtype: float64